// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/alcb1310/final-bca-go/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: p
func (_m *Service) CreateProject(p types.Project) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Project) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type Service_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - p types.Project
func (_e *Service_Expecter) CreateProject(p interface{}) *Service_CreateProject_Call {
	return &Service_CreateProject_Call{Call: _e.mock.On("CreateProject", p)}
}

func (_c *Service_CreateProject_Call) Run(run func(p types.Project)) *Service_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Project))
	})
	return _c
}

func (_c *Service_CreateProject_Call) Return(_a0 error) *Service_CreateProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateProject_Call) RunAndReturn(run func(types.Project) error) *Service_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function with no fields
func (_m *Service) GetHealth() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type Service_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
func (_e *Service_Expecter) GetHealth() *Service_GetHealth_Call {
	return &Service_GetHealth_Call{Call: _e.mock.On("GetHealth")}
}

func (_c *Service_GetHealth_Call) Run(run func()) *Service_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetHealth_Call) Return(_a0 bool) *Service_GetHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_GetHealth_Call) RunAndReturn(run func() bool) *Service_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
