// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/alcb1310/final-bca-go/internal/types"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateBudgetItem provides a mock function with given fields: bi
func (_m *Service) CreateBudgetItem(bi types.CreateBudgetItem) error {
	ret := _m.Called(bi)

	if len(ret) == 0 {
		panic("no return value specified for CreateBudgetItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.CreateBudgetItem) error); ok {
		r0 = rf(bi)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateBudgetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBudgetItem'
type Service_CreateBudgetItem_Call struct {
	*mock.Call
}

// CreateBudgetItem is a helper method to define mock.On call
//   - bi types.CreateBudgetItem
func (_e *Service_Expecter) CreateBudgetItem(bi interface{}) *Service_CreateBudgetItem_Call {
	return &Service_CreateBudgetItem_Call{Call: _e.mock.On("CreateBudgetItem", bi)}
}

func (_c *Service_CreateBudgetItem_Call) Run(run func(bi types.CreateBudgetItem)) *Service_CreateBudgetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.CreateBudgetItem))
	})
	return _c
}

func (_c *Service_CreateBudgetItem_Call) Return(_a0 error) *Service_CreateBudgetItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateBudgetItem_Call) RunAndReturn(run func(types.CreateBudgetItem) error) *Service_CreateBudgetItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCategory provides a mock function with given fields: cat
func (_m *Service) CreateCategory(cat types.Category) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Category) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type Service_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - cat types.Category
func (_e *Service_Expecter) CreateCategory(cat interface{}) *Service_CreateCategory_Call {
	return &Service_CreateCategory_Call{Call: _e.mock.On("CreateCategory", cat)}
}

func (_c *Service_CreateCategory_Call) Run(run func(cat types.Category)) *Service_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Category))
	})
	return _c
}

func (_c *Service_CreateCategory_Call) Return(_a0 error) *Service_CreateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateCategory_Call) RunAndReturn(run func(types.Category) error) *Service_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMaterial provides a mock function with given fields: mat
func (_m *Service) CreateMaterial(mat types.Materials) error {
	ret := _m.Called(mat)

	if len(ret) == 0 {
		panic("no return value specified for CreateMaterial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Materials) error); ok {
		r0 = rf(mat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateMaterial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMaterial'
type Service_CreateMaterial_Call struct {
	*mock.Call
}

// CreateMaterial is a helper method to define mock.On call
//   - mat types.Materials
func (_e *Service_Expecter) CreateMaterial(mat interface{}) *Service_CreateMaterial_Call {
	return &Service_CreateMaterial_Call{Call: _e.mock.On("CreateMaterial", mat)}
}

func (_c *Service_CreateMaterial_Call) Run(run func(mat types.Materials)) *Service_CreateMaterial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Materials))
	})
	return _c
}

func (_c *Service_CreateMaterial_Call) Return(_a0 error) *Service_CreateMaterial_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateMaterial_Call) RunAndReturn(run func(types.Materials) error) *Service_CreateMaterial_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function with given fields: p
func (_m *Service) CreateProject(p types.Project) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Project) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type Service_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - p types.Project
func (_e *Service_Expecter) CreateProject(p interface{}) *Service_CreateProject_Call {
	return &Service_CreateProject_Call{Call: _e.mock.On("CreateProject", p)}
}

func (_c *Service_CreateProject_Call) Run(run func(p types.Project)) *Service_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Project))
	})
	return _c
}

func (_c *Service_CreateProject_Call) Return(_a0 error) *Service_CreateProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateProject_Call) RunAndReturn(run func(types.Project) error) *Service_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSupplier provides a mock function with given fields: sup
func (_m *Service) CreateSupplier(sup types.Supplier) error {
	ret := _m.Called(sup)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Supplier) error); ok {
		r0 = rf(sup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSupplier'
type Service_CreateSupplier_Call struct {
	*mock.Call
}

// CreateSupplier is a helper method to define mock.On call
//   - sup types.Supplier
func (_e *Service_Expecter) CreateSupplier(sup interface{}) *Service_CreateSupplier_Call {
	return &Service_CreateSupplier_Call{Call: _e.mock.On("CreateSupplier", sup)}
}

func (_c *Service_CreateSupplier_Call) Run(run func(sup types.Supplier)) *Service_CreateSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Supplier))
	})
	return _c
}

func (_c *Service_CreateSupplier_Call) Return(_a0 error) *Service_CreateSupplier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateSupplier_Call) RunAndReturn(run func(types.Supplier) error) *Service_CreateSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMaterial provides a mock function with given fields: id
func (_m *Service) DeleteMaterial(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMaterial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteMaterial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMaterial'
type Service_DeleteMaterial_Call struct {
	*mock.Call
}

// DeleteMaterial is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) DeleteMaterial(id interface{}) *Service_DeleteMaterial_Call {
	return &Service_DeleteMaterial_Call{Call: _e.mock.On("DeleteMaterial", id)}
}

func (_c *Service_DeleteMaterial_Call) Run(run func(id uuid.UUID)) *Service_DeleteMaterial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_DeleteMaterial_Call) Return(_a0 error) *Service_DeleteMaterial_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteMaterial_Call) RunAndReturn(run func(uuid.UUID) error) *Service_DeleteMaterial_Call {
	_c.Call.Return(run)
	return _c
}

// GetBudgetItem provides a mock function with given fields: id
func (_m *Service) GetBudgetItem(id uuid.UUID) (types.BudgetItem, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBudgetItem")
	}

	var r0 types.BudgetItem
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (types.BudgetItem, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) types.BudgetItem); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.BudgetItem)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBudgetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBudgetItem'
type Service_GetBudgetItem_Call struct {
	*mock.Call
}

// GetBudgetItem is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) GetBudgetItem(id interface{}) *Service_GetBudgetItem_Call {
	return &Service_GetBudgetItem_Call{Call: _e.mock.On("GetBudgetItem", id)}
}

func (_c *Service_GetBudgetItem_Call) Run(run func(id uuid.UUID)) *Service_GetBudgetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetBudgetItem_Call) Return(_a0 types.BudgetItem, _a1 error) *Service_GetBudgetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBudgetItem_Call) RunAndReturn(run func(uuid.UUID) (types.BudgetItem, error)) *Service_GetBudgetItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetBudgetItems provides a mock function with no fields
func (_m *Service) GetBudgetItems() ([]types.BudgetItem, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBudgetItems")
	}

	var r0 []types.BudgetItem
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.BudgetItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.BudgetItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.BudgetItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBudgetItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBudgetItems'
type Service_GetBudgetItems_Call struct {
	*mock.Call
}

// GetBudgetItems is a helper method to define mock.On call
func (_e *Service_Expecter) GetBudgetItems() *Service_GetBudgetItems_Call {
	return &Service_GetBudgetItems_Call{Call: _e.mock.On("GetBudgetItems")}
}

func (_c *Service_GetBudgetItems_Call) Run(run func()) *Service_GetBudgetItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetBudgetItems_Call) Return(_a0 []types.BudgetItem, _a1 error) *Service_GetBudgetItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBudgetItems_Call) RunAndReturn(run func() ([]types.BudgetItem, error)) *Service_GetBudgetItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetBudgetItemsByAccumulate provides a mock function with given fields: accum
func (_m *Service) GetBudgetItemsByAccumulate(accum bool) ([]types.BudgetItem, error) {
	ret := _m.Called(accum)

	if len(ret) == 0 {
		panic("no return value specified for GetBudgetItemsByAccumulate")
	}

	var r0 []types.BudgetItem
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) ([]types.BudgetItem, error)); ok {
		return rf(accum)
	}
	if rf, ok := ret.Get(0).(func(bool) []types.BudgetItem); ok {
		r0 = rf(accum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.BudgetItem)
		}
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(accum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBudgetItemsByAccumulate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBudgetItemsByAccumulate'
type Service_GetBudgetItemsByAccumulate_Call struct {
	*mock.Call
}

// GetBudgetItemsByAccumulate is a helper method to define mock.On call
//   - accum bool
func (_e *Service_Expecter) GetBudgetItemsByAccumulate(accum interface{}) *Service_GetBudgetItemsByAccumulate_Call {
	return &Service_GetBudgetItemsByAccumulate_Call{Call: _e.mock.On("GetBudgetItemsByAccumulate", accum)}
}

func (_c *Service_GetBudgetItemsByAccumulate_Call) Run(run func(accum bool)) *Service_GetBudgetItemsByAccumulate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Service_GetBudgetItemsByAccumulate_Call) Return(_a0 []types.BudgetItem, _a1 error) *Service_GetBudgetItemsByAccumulate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBudgetItemsByAccumulate_Call) RunAndReturn(run func(bool) ([]types.BudgetItem, error)) *Service_GetBudgetItemsByAccumulate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function with no fields
func (_m *Service) GetCategories() ([]types.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []types.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type Service_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
func (_e *Service_Expecter) GetCategories() *Service_GetCategories_Call {
	return &Service_GetCategories_Call{Call: _e.mock.On("GetCategories")}
}

func (_c *Service_GetCategories_Call) Run(run func()) *Service_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetCategories_Call) Return(_a0 []types.Category, _a1 error) *Service_GetCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetCategories_Call) RunAndReturn(run func() ([]types.Category, error)) *Service_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function with given fields: id
func (_m *Service) GetCategory(id uuid.UUID) (types.Category, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 types.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (types.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) types.Category); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.Category)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type Service_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) GetCategory(id interface{}) *Service_GetCategory_Call {
	return &Service_GetCategory_Call{Call: _e.mock.On("GetCategory", id)}
}

func (_c *Service_GetCategory_Call) Run(run func(id uuid.UUID)) *Service_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetCategory_Call) Return(_a0 types.Category, _a1 error) *Service_GetCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetCategory_Call) RunAndReturn(run func(uuid.UUID) (types.Category, error)) *Service_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function with no fields
func (_m *Service) GetHealth() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type Service_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
func (_e *Service_Expecter) GetHealth() *Service_GetHealth_Call {
	return &Service_GetHealth_Call{Call: _e.mock.On("GetHealth")}
}

func (_c *Service_GetHealth_Call) Run(run func()) *Service_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetHealth_Call) Return(_a0 bool) *Service_GetHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_GetHealth_Call) RunAndReturn(run func() bool) *Service_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetItems provides a mock function with no fields
func (_m *Service) GetItems() ([]types.Items, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetItems")
	}

	var r0 []types.Items
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Items, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Items); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Items)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItems'
type Service_GetItems_Call struct {
	*mock.Call
}

// GetItems is a helper method to define mock.On call
func (_e *Service_Expecter) GetItems() *Service_GetItems_Call {
	return &Service_GetItems_Call{Call: _e.mock.On("GetItems")}
}

func (_c *Service_GetItems_Call) Run(run func()) *Service_GetItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetItems_Call) Return(_a0 []types.Items, _a1 error) *Service_GetItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetItems_Call) RunAndReturn(run func() ([]types.Items, error)) *Service_GetItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaterial provides a mock function with given fields: id
func (_m *Service) GetMaterial(id uuid.UUID) (types.Materials, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetMaterial")
	}

	var r0 types.Materials
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (types.Materials, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) types.Materials); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.Materials)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetMaterial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaterial'
type Service_GetMaterial_Call struct {
	*mock.Call
}

// GetMaterial is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) GetMaterial(id interface{}) *Service_GetMaterial_Call {
	return &Service_GetMaterial_Call{Call: _e.mock.On("GetMaterial", id)}
}

func (_c *Service_GetMaterial_Call) Run(run func(id uuid.UUID)) *Service_GetMaterial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetMaterial_Call) Return(_a0 types.Materials, _a1 error) *Service_GetMaterial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetMaterial_Call) RunAndReturn(run func(uuid.UUID) (types.Materials, error)) *Service_GetMaterial_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaterials provides a mock function with no fields
func (_m *Service) GetMaterials() ([]types.Materials, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaterials")
	}

	var r0 []types.Materials
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Materials, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Materials); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Materials)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetMaterials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaterials'
type Service_GetMaterials_Call struct {
	*mock.Call
}

// GetMaterials is a helper method to define mock.On call
func (_e *Service_Expecter) GetMaterials() *Service_GetMaterials_Call {
	return &Service_GetMaterials_Call{Call: _e.mock.On("GetMaterials")}
}

func (_c *Service_GetMaterials_Call) Run(run func()) *Service_GetMaterials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetMaterials_Call) Return(_a0 []types.Materials, _a1 error) *Service_GetMaterials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetMaterials_Call) RunAndReturn(run func() ([]types.Materials, error)) *Service_GetMaterials_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: id
func (_m *Service) GetProject(id uuid.UUID) (types.Project, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 types.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (types.Project, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) types.Project); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.Project)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type Service_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) GetProject(id interface{}) *Service_GetProject_Call {
	return &Service_GetProject_Call{Call: _e.mock.On("GetProject", id)}
}

func (_c *Service_GetProject_Call) Run(run func(id uuid.UUID)) *Service_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetProject_Call) Return(_a0 types.Project, _a1 error) *Service_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProject_Call) RunAndReturn(run func(uuid.UUID) (types.Project, error)) *Service_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function with no fields
func (_m *Service) GetProjects() ([]types.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProjects")
	}

	var r0 []types.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type Service_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
func (_e *Service_Expecter) GetProjects() *Service_GetProjects_Call {
	return &Service_GetProjects_Call{Call: _e.mock.On("GetProjects")}
}

func (_c *Service_GetProjects_Call) Run(run func()) *Service_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetProjects_Call) Return(_a0 []types.Project, _a1 error) *Service_GetProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProjects_Call) RunAndReturn(run func() ([]types.Project, error)) *Service_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupplier provides a mock function with given fields: id
func (_m *Service) GetSupplier(id uuid.UUID) (types.Supplier, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSupplier")
	}

	var r0 types.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (types.Supplier, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) types.Supplier); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.Supplier)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupplier'
type Service_GetSupplier_Call struct {
	*mock.Call
}

// GetSupplier is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Service_Expecter) GetSupplier(id interface{}) *Service_GetSupplier_Call {
	return &Service_GetSupplier_Call{Call: _e.mock.On("GetSupplier", id)}
}

func (_c *Service_GetSupplier_Call) Run(run func(id uuid.UUID)) *Service_GetSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetSupplier_Call) Return(_a0 types.Supplier, _a1 error) *Service_GetSupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetSupplier_Call) RunAndReturn(run func(uuid.UUID) (types.Supplier, error)) *Service_GetSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// GetSuppliers provides a mock function with no fields
func (_m *Service) GetSuppliers() ([]types.Supplier, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSuppliers")
	}

	var r0 []types.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Supplier, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Supplier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetSuppliers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSuppliers'
type Service_GetSuppliers_Call struct {
	*mock.Call
}

// GetSuppliers is a helper method to define mock.On call
func (_e *Service_Expecter) GetSuppliers() *Service_GetSuppliers_Call {
	return &Service_GetSuppliers_Call{Call: _e.mock.On("GetSuppliers")}
}

func (_c *Service_GetSuppliers_Call) Run(run func()) *Service_GetSuppliers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_GetSuppliers_Call) Return(_a0 []types.Supplier, _a1 error) *Service_GetSuppliers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetSuppliers_Call) RunAndReturn(run func() ([]types.Supplier, error)) *Service_GetSuppliers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBudgetItem provides a mock function with given fields: bi
func (_m *Service) UpdateBudgetItem(bi types.UpdateBudgetItem) error {
	ret := _m.Called(bi)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBudgetItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UpdateBudgetItem) error); ok {
		r0 = rf(bi)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateBudgetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBudgetItem'
type Service_UpdateBudgetItem_Call struct {
	*mock.Call
}

// UpdateBudgetItem is a helper method to define mock.On call
//   - bi types.UpdateBudgetItem
func (_e *Service_Expecter) UpdateBudgetItem(bi interface{}) *Service_UpdateBudgetItem_Call {
	return &Service_UpdateBudgetItem_Call{Call: _e.mock.On("UpdateBudgetItem", bi)}
}

func (_c *Service_UpdateBudgetItem_Call) Run(run func(bi types.UpdateBudgetItem)) *Service_UpdateBudgetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UpdateBudgetItem))
	})
	return _c
}

func (_c *Service_UpdateBudgetItem_Call) Return(_a0 error) *Service_UpdateBudgetItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateBudgetItem_Call) RunAndReturn(run func(types.UpdateBudgetItem) error) *Service_UpdateBudgetItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: cat
func (_m *Service) UpdateCategory(cat types.Category) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Category) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type Service_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - cat types.Category
func (_e *Service_Expecter) UpdateCategory(cat interface{}) *Service_UpdateCategory_Call {
	return &Service_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", cat)}
}

func (_c *Service_UpdateCategory_Call) Run(run func(cat types.Category)) *Service_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Category))
	})
	return _c
}

func (_c *Service_UpdateCategory_Call) Return(_a0 error) *Service_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateCategory_Call) RunAndReturn(run func(types.Category) error) *Service_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMaterial provides a mock function with given fields: mat
func (_m *Service) UpdateMaterial(mat types.Materials) error {
	ret := _m.Called(mat)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMaterial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Materials) error); ok {
		r0 = rf(mat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateMaterial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMaterial'
type Service_UpdateMaterial_Call struct {
	*mock.Call
}

// UpdateMaterial is a helper method to define mock.On call
//   - mat types.Materials
func (_e *Service_Expecter) UpdateMaterial(mat interface{}) *Service_UpdateMaterial_Call {
	return &Service_UpdateMaterial_Call{Call: _e.mock.On("UpdateMaterial", mat)}
}

func (_c *Service_UpdateMaterial_Call) Run(run func(mat types.Materials)) *Service_UpdateMaterial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Materials))
	})
	return _c
}

func (_c *Service_UpdateMaterial_Call) Return(_a0 error) *Service_UpdateMaterial_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateMaterial_Call) RunAndReturn(run func(types.Materials) error) *Service_UpdateMaterial_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: p
func (_m *Service) UpdateProject(p types.Project) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Project) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type Service_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - p types.Project
func (_e *Service_Expecter) UpdateProject(p interface{}) *Service_UpdateProject_Call {
	return &Service_UpdateProject_Call{Call: _e.mock.On("UpdateProject", p)}
}

func (_c *Service_UpdateProject_Call) Run(run func(p types.Project)) *Service_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Project))
	})
	return _c
}

func (_c *Service_UpdateProject_Call) Return(_a0 error) *Service_UpdateProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateProject_Call) RunAndReturn(run func(types.Project) error) *Service_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSupplier provides a mock function with given fields: sup
func (_m *Service) UpdateSupplier(sup types.Supplier) error {
	ret := _m.Called(sup)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Supplier) error); ok {
		r0 = rf(sup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSupplier'
type Service_UpdateSupplier_Call struct {
	*mock.Call
}

// UpdateSupplier is a helper method to define mock.On call
//   - sup types.Supplier
func (_e *Service_Expecter) UpdateSupplier(sup interface{}) *Service_UpdateSupplier_Call {
	return &Service_UpdateSupplier_Call{Call: _e.mock.On("UpdateSupplier", sup)}
}

func (_c *Service_UpdateSupplier_Call) Run(run func(sup types.Supplier)) *Service_UpdateSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Supplier))
	})
	return _c
}

func (_c *Service_UpdateSupplier_Call) Return(_a0 error) *Service_UpdateSupplier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateSupplier_Call) RunAndReturn(run func(types.Supplier) error) *Service_UpdateSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
